/** Tool-role V3-to-V4 migration with native V4 framing and delivery validation. */

export { releasedV3SessionFormatCodec } from '@deepseek-ai/dsh-session-format-v2-to-v3'
export * from './codec.ts'
export * from './migration.ts'
export { assertReleasedV4Header, assertReleasedV4Relationships, restoreReleasedV4Artifact } from './validation.ts'
export { historicalChildCatalogSource } from './facts.ts'
export { RELEASED_V3_EVENT_TYPES } from './extension-identities.ts'
export { assertV4DeveloperData } from './developer.ts'
export { assertV4LifecycleRelationships, assertLifecycleRelationshipsWithAbandonedSteps } from './relationships.ts'
export { assertV4MessageSources } from './message-sources.ts'
export { catalogFact } from './facts.ts'
export { assertV4RetiredSyntax } from './retired-syntax.ts'
export { assertV4SystemMessageFields } from './system-message.ts'
export { assertV4ForkResult } from './fork-result.ts'
export { assertV4ToolResultMessage } from './tool-role.ts'
export { mapEventMessages } from './sources.ts'
